<a href="https://colab.research.google.com/github/luizhenriquesb/alura-data-science/blob/main/nivel_1/01_pandas.ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Bibliotecas

In [1]:
import pandas as pd

## 2. Importação

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv', sep=';')

## 3. Análise Exploratória

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32960 non-null  object
 1   Bairro      32960 non-null  object
 2   Quartos     32960 non-null  int64
 3   Vagas       32960 non-null  int64
 4   Suites      32960 non-null  int64
 5   Area        32960 non-null  int64
 6   Valor       32943 non-null  float64
 7   Condominio  28867 non-null  float64
 8   IPTU        22723 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.3+ MB

In [7]:
# Média da coluna 'valor'
df.Valor.mean()

np.float64(12952.659715265761)

In [23]:
# Média de valor por 'tipo'
(
    df
      .groupby('Tipo')
      .agg(media = ('Valor', 'mean'))
      .reset_index()
      .sort_values(by='media', ascending=False)
)

                           Tipo          media
17               Prédio Inteiro  498637.239203
11                    Indústria  120000.000000
9       Galpão/Depósito/Armazém   53407.062600
21               Terreno Padrão   32567.714286
10                        Hotel   25000.000000
15        Loteamento/Condomínio   22000.000000
7       Conjunto Comercial/Sala   14715.045521
3                Casa Comercial   14478.264151
14                   Loja/Salão   13769.646770
20                        Sítio   12499.000000
4            Casa de Condomínio   11952.061245
13  Loja Shopping/ Ct Comercial    8126.178862
2                          Casa    6793.454922
6                       Chácara    4900.000000
0                   Apartamento    4744.614648
8                          Flat    4546.189076
12                         Loft    2557.882353
19                       Studio    2400.000000
1                   Box/Garagem    1899.756098
5                  Casa de Vila    1574.369478
16                Pousada/Chalé    1480.000000
18                    Quitinete    1246.840909

In [39]:
# Percentual de cada imóvel

# Jeito 1
# (
#     df
#       .value_counts('Tipo')
#       .reset_index()
#       .assign(perc = lambda x: x['count'] / x['count'].sum())
# )

# Jeito 2
(
    df
      .value_counts('Tipo', normalize=True)
      .reset_index()
      .sort_values(by='proportion', ascending=False)
)

                           Tipo  proportion
0                   Apartamento    0.592597
1       Conjunto Comercial/Sala    0.206766
2                    Loja/Salão    0.043265
3            Casa de Condomínio    0.030218
4                          Casa    0.029339
5                     Quitinete    0.025364
6       Galpão/Depósito/Armazém    0.018902
7                          Flat    0.014442
8                Prédio Inteiro    0.009132
9                Casa Comercial    0.008040
10                 Casa de Vila    0.007555
11  Loja Shopping/ Ct Comercial    0.007494
12                  Box/Garagem    0.002488
13               Terreno Padrão    0.002124
14                         Loft    0.001547
15                        Sítio    0.000303
16        Loteamento/Condomínio    0.000152
17                       Studio    0.000121
18                        Hotel    0.000061
19                      Chácara    0.000030
20                    Indústria    0.000030
21                Pousada/Chalé    0.000030